source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'shared', :path => '../shared'
end

target 'iosApp' do
  shared_pods
end

# https://github.com/nicklockwood/SwiftFormat
pod 'SwiftFormat/CLI', '~> 0.53.9'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
