package com.ding1ding.app.shared.redwood.composeui

import androidx.compose.ui.graphics.Color

// hex: #30A14E => rgba(48, 161, 78, 1)
const val hexSeedColor = "#30A14E"

val navigationBarColorLight = Color(0xFFF7F7F7)
val navigationBarColorDark = Color(0xFF1E1E1E)

val background_light = Color(0xFFEDEDED)
val background_dark = Color(0xFF111111)

val primaryLight = Color(0xFF36693E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB8F1B9)
val onPrimaryContainerLight = Color(0xFF002108)
val secondaryLight = Color(0xFF516351)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD4E8D1)
val onSecondaryContainerLight = Color(0xFF0F1F11)
val tertiaryLight = Color(0xFF39656C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBDEAF3)
val onTertiaryContainerLight = Color(0xFF001F24)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = background_light
val onBackgroundLight = Color(0xFF181D18)
val surfaceLight = background_light
val onSurfaceLight = Color(0xFF181D18)
val surfaceVariantLight = Color(0xFFDDE5D9)
val onSurfaceVariantLight = Color(0xFF424940)
val outlineLight = Color(0xFF727970)
val outlineVariantLight = Color(0xFFC1C9BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D322C)
val inverseOnSurfaceLight = Color(0xFFEEF2E9)
val inversePrimaryLight = Color(0xFF9CD49F)
val surfaceDimLight = background_light
val surfaceBrightLight = Color(0xFFF7FBF2)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5EC)
val surfaceContainerLight = Color(0xFFEBEFE7)
val surfaceContainerHighLight = Color(0xFFE5E9E1)
val surfaceContainerHighestLight = Color(0xFFE0E4DB)

val primaryDark = Color(0xFF9CD49F)
val onPrimaryDark = Color(0xFF003913)
val primaryContainerDark = Color(0xFF1D5128)
val onPrimaryContainerDark = Color(0xFFB8F1B9)
val secondaryDark = Color(0xFFB8CCB5)
val onSecondaryDark = Color(0xFF243425)
val secondaryContainerDark = Color(0xFF3A4B3A)
val onSecondaryContainerDark = Color(0xFFD4E8D1)
val tertiaryDark = Color(0xFFA1CED6)
val onTertiaryDark = Color(0xFF00363D)
val tertiaryContainerDark = Color(0xFF1F4D54)
val onTertiaryContainerDark = Color(0xFFBDEAF3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = background_dark
val onBackgroundDark = Color(0xFFE0E4DB)
val surfaceDark = background_dark
val onSurfaceDark = Color(0xFFE0E4DB)
val surfaceVariantDark = Color(0xFF424940)
val onSurfaceVariantDark = Color(0xFFC1C9BE)
val outlineDark = Color(0xFF8B9389)
val outlineVariantDark = Color(0xFF424940)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E4DB)
val inverseOnSurfaceDark = Color(0xFF2D322C)
val inversePrimaryDark = Color(0xFF36693E)
val surfaceDimDark = background_dark
val surfaceBrightDark = Color(0xFF363A35)
val surfaceContainerLowestDark = Color(0xFF0B0F0B)
val surfaceContainerLowDark = Color(0xFF181D18)
val surfaceContainerDark = Color(0xFF1C211C)
val surfaceContainerHighDark = Color(0xFF272B26)
val surfaceContainerHighestDark = Color(0xFF313630)
